name: "Continuous Integration"

on:
  push:
  pull_request:
    branches: [ master ]

env:
  AREA: liechtenstein

jobs:
  generate-tiles:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download PBF file
      run: curl http://download.geofabrik.de/europe/${AREA}-latest.osm.pbf -o ${AREA}.osm.pbf

    - name: Build openmaptiles-compatible mbtiles files of given area
      uses: ./
      with:
        input: ${{ env.AREA }}.osm.pbf 
        output: ${{ env.AREA }}.mbtiles
